HPRMSYSTEM/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('users/', include('django.contrib.auth.urls')),
                  path('', include('users.urls')),
                  path('users/', include('users.urls')),
                  path('problems_report/', include('problems_report.urls')),
                  path('hostel/', include('hostel.urls')),
                #   path('hostel_block/', include('hostel_block.urls'))

              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hostel/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('register_hostel/', views.register_hostel, name='register_hostel'),
    path('hostel-list/', views.view_hostel, name='hostel-list'),
    path('update-hostel/<hostel_id>', views.update_hostel, name='update-hostel'),
    path('delete-hostel/<hostel_id>', views.delete_hostel, name='delete-hostel'),
    path('register_block/', views.register_hostel_block, name='register_block'),
    path('Blocks-list/', views.view_hostel_blocks, name='Blocks-list'),
    path('update-block/<hostel_block_id>', views.update_block, name='update-block'),
    path('delete-block/<hostel_block_id>', views.delete_block, name='delete-block'),
    path('register-room/', views.register_room, name='register-room'),
    path('rooms-registered/', views.view_rooms, name='rooms-registered'),
    path('update-room/<room_id>', views.update_room, name='update-room'),
    path('delete-room/<room_id>', views.delete_room, name='delete-room'),
    path('allocate-student-room/', views.allocate_room_student, name='allocate-student-room'),
    path('allocate-warden-block/', views.allocate_block_warden, name='allocate-warden-block'),
    path('student-allocations/', views.view_student_allocation, name='student-allocations'),
    path('warden-allocations/', views.view_warden_allocation, name='warden-allocations'),
    path('update-student-allocation/<allocate_room_id>', views.update_student_allocation_room, name='update-student-allocation'),
    path('delete-student-allocation/<allocate_room_id>', views.delete_student_allocation_room, name='delete-student-allocation'),
    path('update-warden-allocation/<allocate_block_id>', views.update_warden_allocation, name='update-warden-allocation'),
    path('delete-warden-allocation/<allocate_block_id>', views.delete_warden_allocation, name='delete-warden-allocation'),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView, PasswordChangeDoneView
from django.contrib.auth.views import PasswordResetView, PasswordResetConfirmView, PasswordResetDoneView
from django.contrib.auth.views import PasswordResetCompleteView
from django.urls import path, reverse_lazy
from . import views

urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('register/', views.user_register, name='register'),
    path('add_student/', views.add_student, name='add_student'),
    path('add_warden/', views.add_warden, name='add_warden'),
    path('users-list/', views.users_view, name='users-list'),
    path('update-student/<student_id>', views.update_student, name='update-student'),
    path('delete-student/<student_id>', views.delete_student, name='delete-student'),
    path('warden-list/', views.view_wardens, name='warden-list'),
    path('students-list/', views.view_students, name='students-list'),
    path('update-warden/<warden_id>', views.update_warden, name='update-warden'),
    path('delete-warden/<warden_id>', views.delete_warden, name='delete-warden'),
    path('dashboard/', views.homepage, name='dashboard'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('change-password/', PasswordChangeView.as_view(
        template_name='users/password_change.html',
        success_url=reverse_lazy('password_change_done')), name='change-password'),
    path('change password/done/', PasswordChangeDoneView.as_view(
        template_name='users/password_change_done.html'), name='password_change_done'),
    path('password reset/', PasswordResetView.as_view(template_name='users/password_reset_form.html'),
         name='password_reset'),
    path('password reset done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path(r'<uidb64>[0-9A-Za-z_\-]+/<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20}/$',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password reset complete/', PasswordResetCompleteView.as_view(
        template_name='users/password_reset_complete.html'), name='password_reset_complete')
]

hostel/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class hostel(models.Model):
    name = models.CharField(max_length=100)
    location = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, default='', on_delete=models.CASCADE)
    updated_at = models.DateTimeField(auto_now=True)
    objects = models.Manager()
    
    def __str__(self):
        return self.name


class hostel_block(models.Model):
    block_name = models.CharField(max_length=20)
    hostel_name = models.ForeignKey(hostel, default='', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, default='', on_delete=models.CASCADE)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.block_name


class room(models.Model):
    room_no = models.CharField(max_length=6)
    block_name = models.ForeignKey(hostel_block, default='', on_delete=models.CASCADE)
    hostel_name = models.ForeignKey(hostel, default='', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, default='', on_delete=models.CASCADE)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.room_no


class allocate_room(models.Model):
    student = models.ForeignKey(User, default='', on_delete=models.CASCADE)
    room = models.ForeignKey(room, default='', on_delete=models.CASCADE)
    block_name = models.ForeignKey(hostel_block, default='', on_delete=models.CASCADE)
    hostel_name = models.ForeignKey(hostel, default='', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.student


class allocate_block(models.Model):
    warden = models.ForeignKey(User, default='', on_delete=models.CASCADE)
    block_name = models.ForeignKey(hostel_block, default='', on_delete=models.CASCADE)
    hostel_name = models.ForeignKey(hostel, default='', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.warden

hostel/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import hostel, hostel_block, room, allocate_block, allocate_room

# student problem report form
class registerHostelForm(forms.ModelForm):
    created_by = forms.ModelChoiceField(queryset=User.objects.all(), widget=forms.HiddenInput())

    class Meta:
        model = hostel
        fields = ('created_by', 'name', 'location')


class registerBlockForm(forms.ModelForm):
    created_by = forms.ModelChoiceField(queryset=User.objects.all(), widget=forms.HiddenInput())

    class Meta:
        model = hostel_block
        fields = ('created_by', 'block_name', 'hostel_name')


class registerRoomForm(forms.ModelForm):
    created_by = forms.ModelChoiceField(queryset=User.objects.all(), widget=forms.HiddenInput())

    class Meta:
        model = room
        fields = ('created_by', 'room_no', 'block_name', 'hostel_name')


class allocateRoomForm(forms.ModelForm):
    student = forms.ModelChoiceField(queryset=User.objects.filter(is_staff=0, is_superuser = 0))

    class Meta:
        model = allocate_room
        fields = ('student', 'room', 'block_name', 'hostel_name')


class allocateBlockForm(forms.ModelForm):
    warden = forms.ModelChoiceField(queryset=User.objects.filter(is_staff=1, is_superuser = 0))

    class Meta:
        model = allocate_block
        fields = ('warden', 'block_name', 'hostel_name')

hostel/views.py
from django.shortcuts import render
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse
from .forms import registerHostelForm, registerBlockForm, registerRoomForm, allocateBlockForm, allocateRoomForm
from .models import allocate_block, allocate_room, hostel, hostel_block, room
from django.contrib.auth.models import User
from django.conf import settings

# Create your views here.


def register_hostel(request):

    form = registerHostelForm(request.POST)
    if form.is_valid():
        form.save()
        instance = form.save(commit=False)
        instance.created_by = request.user
        instance.save()
        messages.success(request, " New hostel has been added successful")

        return redirect('register_hostel')

    return render(request, 'hostel/register_hostel.html', {'form':form})


def view_hostel(request):

    htl = hostel.objects.all()

    context = {

        'hostel': htl,
    }
    return render(request, 'hostel/hostel.html', context)


@login_required
def register_hostel_block(request):

    form = registerBlockForm(request.POST)
    if request.method == 'POST':
        if form.is_valid:
            form.save
            instance = form.save(commit=False)
            instance.created_by = request.user
            instance.save()
            messages.success(request, "New hostel block has been added successfully")

            return redirect('register_block')

    return render(request, 'hostel/register_block.html', {'form':form})


@login_required
def register_room(request):

    form = registerRoomForm(request.POST)
    if request.method == 'POST':
        if form.is_valid:
            form.save
            instance = form.save(commit=False)
            instance.created_by = request.user
            instance.save()
            messages.success(request, "New room has been added successfully")

            return redirect('register-room')

    return render(request, 'hostel/register_room.html', {'form':form})


@login_required
def view_rooms(request):

    view_room_block = room.objects.all()

    context = {
        'room': view_room_block
    }

    return render(request, 'hostel/rooms.html', context)


@login_required
def view_hostel_blocks(request):

    view_htl_block = hostel_block.objects.all()

    context = {
        'hostel_block': view_htl_block
    }

    return render(request, 'hostel/view_blocks.html', context)
    

@login_required
def update_hostel(request, hostel_id):
    students_hostel = hostel.objects.get(pk=hostel_id)
    form = registerHostelForm(request.POST or None, instance=students_hostel)
    if form.is_valid():
        form.save()
        instance = form.save(commit=False)
        instance.created_by = request.user
        instance.save()
        messages.success(request, " hostel has been updated successful")

        return redirect('hostel-list')
    
    context = {
        'form':form,
    }

    return render(request, 'hostel/update_hostel.html', context)


@login_required
def delete_hostel(request, hostel_id):
    hostel_del = hostel.objects.get(pk=hostel_id)
    hostel_del.delete()
    return redirect('hostel-list')


@login_required
def update_block(request, hostel_block_id):
    students_block = hostel_block.objects.get(pk=hostel_block_id)
    form = registerBlockForm(request.POST or None, instance=students_block)
    if form.is_valid():
        form.save()
        instance = form.save(commit=False)
        instance.created_by = request.user
        instance.save()
        messages.success(request, " hostel Block has been updated successful")

        return redirect('Blocks-list')
    
    context = {
        'form':form,
    }

    return render(request, 'hostel/update_block.html', context)


@login_required
def delete_block(request, hostel_block_id):
    hostel_block_del = hostel_block.objects.get(pk=hostel_block_id)
    hostel_block_del.delete()
    return redirect('blocks-list')


@login_required
def update_room(request, room_id):
    students_room = room.objects.get(pk=room_id)
    form = registerRoomForm(request.POST or None, instance=students_room)
    if form.is_valid():
        form.save()
        instance = form.save(commit=False)
        instance.created_by = request.user
        instance.save()
        messages.success(request, " Room has been updated successful")

        return redirect('rooms-registered')
    
    context = {
        'form':form,
    }

    return render(request, 'hostel/update_room.html', context)


@login_required
def delete_room(request, room_id):
    room_del = room.objects.get(pk=room_id)
    room_del.delete()
    return redirect('rooms-registered')


@login_required
def allocate_room_student(request):

    form = allocateRoomForm(request.POST)
    if request.method == 'POST':
        if form.is_valid:
            form.save
            instance = form.save(commit=False)
            instance.created_by = request.user
            instance.save()
            messages.success(request, "A student has allocated a room successfully")

            return redirect('allocate-student-room')

    return render(request, 'hostel/allocate_student.html', {'form':form})


@login_required
def allocate_block_warden(request):

    form = allocateBlockForm(request.POST)
    if request.method == 'POST':
        if form.is_valid:
            form.save
            instance = form.save(commit=False)
            instance.created_by = request.user
            instance.save()
            messages.success(request, "A warden has allocated a block successfully")

            return redirect('allocate-warden-block')

    return render(request, 'hostel/allocate_warden.html', {'form':form})


@login_required
def view_student_allocation(request):

    view_st_room = allocate_room.objects.all()

    context = {
        'allocate_room': view_st_room
    }

    return render(request, 'hostel/student_allocation.html', context)


@login_required
def view_warden_allocation(request):

    view_wd_block = allocate_block.objects.all()

    context = {
        'allocate_block': view_wd_block
    }

    return render(request, 'hostel/warden_allocation.html', context)


@login_required
def update_student_allocation_room(request, allocate_room_id):
    allocate_student_room = allocate_room.objects.get(pk=allocate_room_id)
    form = allocateRoomForm(request.POST or None, instance=allocate_student_room)
    if form.is_valid():
        form.save()
        instance = form.save(commit=False)
        instance.created_by = request.user
        instance.save()
        messages.success(request, " Student Allocation has been updated successful")

        return redirect('student-allocations')
    
    context = {
        'form':form,
    }

    return render(request, 'hostel/update_student_allocation.html', context)


@login_required
def delete_student_allocation_room(request, allocate_room_id):
    allocate_room_del = allocate_room.objects.get(pk=allocate_room_id)
    allocate_room_del.delete()
    return redirect('student-allocations')


@login_required
def update_warden_allocation(request, allocate_block_id):
    allocate_warden_block = allocate_block.objects.get(pk=allocate_block_id)
    form = allocateBlockForm(request.POST or None, instance=allocate_warden_block)
    if form.is_valid():
        form.save()
        instance = form.save(commit=False)
        instance.created_by = request.user
        instance.save()
        messages.success(request, " Warden Allocation has been updated successfully")

        return redirect('warden-allocations')
    
    context = {
        'form':form,
    }

    return render(request, 'hostel/update_warden_allocation.html', context)


@login_required
def delete_warden_allocation(request, allocate_block_id):
    allocate_block_del = allocate_block.objects.get(pk=allocate_block_id)
    allocate_block_del.delete()
    return redirect('warden-allocations')

hostel/templates/hostel/hostel.html
{% extends 'users/base.html' %}


{% block title %}
    HPRMS | Hostel
{% endblock title %}

{% load static %}

{% load crispy_forms_tags %}

{% block content %}

<div class="content-header">
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><a href="{% url 'dashboard' %}">Home</a></li>
          <li class="breadcrumb-item active">Hostel</li>
        </ol>
      </div><!-- /.col -->
    </div><!-- /.row -->
  </div><!-- /.container-fluid -->
</div>

<section style="padding-left: 5px; padding-right: 5px;">
<div class="card">
  <div class="card-header">
    <h3 class="card-title"><i>Hostel</i></h3>
  </div>
  <!-- /.card-header -->
  <div class="card-body">
    <table class="table table-bordered table-striped">
      <thead>
      <tr>
        <th>INDEX No</th>
        <th>ID</th>
        <th>Name</th>
        <th>Location</th>
        <th>Created By</th>
        <th>Action</th>
      </tr>
      </thead>
      <tbody>
        {% for htl in hostel %}
        <tr style="background-color: #fff;">
              <td>
                  <strong>
                      {{ forloop.counter }}
                  </strong>
              </td>
              <td>{{htl.id}}</td>
              <td>{{htl.name}}</td>
              <td>{{htl.location}}</td>
              <td>{{htl.created_by}}</td>
              <td>
                <a href="{% url 'update-hostel' htl.id %}" class="btn btn-primary">Update</a>
                <a href="{% url 'delete-hostel' htl.id %}" class="btn btn-danger">Delete</a>
              </td>

            </tr>

        {% endfor %}
      </tbody>
      <tfoot>
      <tr>
        <th>INDEX No</th>
        <th>ID</th>
        <th>Name</th>
        <th>Location</th>
        <th>Created By</th>
        <th>Action</th>
      </tr>
      </tfoot>
    </table>
  </div>
</div>
</section>
{% endblock content %}

hostel/templates/hostel/register_block.html
{% extends 'users/base.html' %}
{% load crispy_forms_tags %}


        {% block title %}
            HPRMS |    Register Hostel Block
        {% endblock title %}
    

{% block content %}
{% load static %}

    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-12">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="{% url 'dashboard' %}">Home</a></li>
              <li class="breadcrumb-item active"><i>Register Hostel Block</i></li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

<section class="h-100 h-custom" style="padding-left: 100px;">

              <div class="card col-lg-10">
                    <div class="card-header">
                      <h3 class="card-title">
                        <i>Register Hostel Block</i>
                      </h3>
                    </div><!-- /.card-header -->
                    <div class="card-body">
                      <div class="tab-content p-0">

                        {% if messages %}
                        {% for message in messages %}

                        <div class="alert alert-success">
                        {{ message }}

                        <button class="closebtn" onclick="this.parentElement.style.display='none';">&times;</button>
                    </div>
                        {% endfor %}
                        {% endif %}

                  <form class="px-md-2" method="POST" action="#">{% csrf_token %}

                  <!--                {{ form|crispy }}-->

                    <input type="hidden" name="created_by" value="1" id="id_created_by" class="form-control" required>

                      <div class="form-group mb-2">
                        <label for="block_name">Block Name</label>
                        <input type="text" name="block_name" id="block_name" class="form-control" required>
                      </div>
    
                      <div class="form-group mb-2">
                        <label for="location">hostel</label>
                        {{ form.hostel_name }}
                      </div>

                  <button type="submit" class="btn btn-primary btn-lg mb-1">Submit</button>

                  </form>

                      </div>
                    </div><!-- /.card-body -->
                  </div>
                  <!-- /.card -->
</section>
{% endblock content %}

hostel/templates/hostel/register_hostel.html
{% extends 'users/base.html' %}
{% load crispy_forms_tags %}


        {% block title %}
            HPRMS |    Register hostel
        {% endblock title %}
    

{% block content %}
{% load static %}

    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-12">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="{% url 'dashboard' %}">Home</a></li>
              <li class="breadcrumb-item active"><i>Register hostel</i></li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

<section class="h-100 h-custom" style="padding-left: 100px;">

              <div class="card col-lg-10">
                    <div class="card-header">
                      <h3 class="card-title">
                        <i>Register hostel</i>
                      </h3>
                    </div><!-- /.card-header -->
                    <div class="card-body">
                      <div class="tab-content p-0">

                        {% if messages %}
                        {% for message in messages %}

                        <div class="alert alert-success">
                        {{ message }}

                        <button class="closebtn" onclick="this.parentElement.style.display='none';">&times;</button>
                    </div>
                        {% endfor %}
                        {% endif %}

                  <form class="px-md-2" method="POST" action="#">{% csrf_token %}

                  <!--                {{ form|crispy }}-->

                    <input type="hidden" name="created_by" value="1" id="id_created_by" class="form-control" required>

                      <div class="form-group mb-2">
                        <label for="name">Name</label>
                        <input type="text" name="name" id="name" class="form-control" required>
                      </div>
    
                      <div class="form-group mb-2">
                        <label for="location">location</label>
                        <input type="text" name="location" id="location" class="form-control" required>
                      </div>

                  <button type="submit" class="btn btn-primary btn-lg mb-1">Submit</button>

                  </form>

                      </div>
                    </div><!-- /.card-body -->
                  </div>
                  <!-- /.card -->
</section>
{% endblock content %}

hostel/templates/hostel/register_room.html
{% extends 'users/base.html' %}
{% load crispy_forms_tags %}


        {% block title %}
            HPRMS |    Register Room
        {% endblock title %}
    

{% block content %}
{% load static %}

    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-12">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="{% url 'dashboard' %}">Home</a></li>
              <li class="breadcrumb-item active"><i>Register Room</i></li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

<section class="h-100 h-custom" style="padding-left: 100px;">

              <div class="card col-lg-10">
                    <div class="card-header">
                      <h3 class="card-title">
                        <i>Register Room</i>
                      </h3>
                    </div>
                    <div class="card-body">
                      <div class="tab-content p-0">

                        {% if messages %}
                        {% for message in messages %}

                        <div class="alert alert-success">
                        {{ message }}

                        <button class="closebtn" onclick="this.parentElement.style.display='none';">&times;</button>
                    </div>
                        {% endfor %}
                        {% endif %}

                  <form class="px-md-2" method="POST" action="#">{% csrf_token %}

                  <!--                {{ form|crispy }}-->

                    <input type="hidden" name="created_by" value="1" id="id_created_by" class="form-control" required>

                      <div class="form-group mb-2">
                        <label for="room_no">Room number</label>
                        <input type="text" name="room_no" id="room_no" class="form-control" required>
                      </div>

                      <div class="form-group mb-2">
                        <label for="block_name">Block name</label>
                        {{ form.block_name }}
                      </div>

                      <div class="form-group mb-2">
                        <label for="hostel_name">Hostel name</label>
                        {{ form.hostel_name }}
                      </div>

                  <button type="submit" class="btn btn-primary btn-lg mb-1">Submit</button>

                  </form>

                      </div>
                    </div>
                  </div>
                  
</section>
{% endblock content %}

hostel/templates/hostel/update_block.html
{% extends 'users/base.html' %}
{% load crispy_forms_tags %}


        {% block title %}
            HPRMS |    Update Hostel Block
        {% endblock title %}
    

{% block content %}
{% load static %}

    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-12">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="{% url 'dashboard' %}">Home</a></li>
              <li class="breadcrumb-item active"><i>Update Hostel Block</i></li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

<section class="h-100 h-custom" style="padding-left: 100px;">

              <div class="card col-lg-10">
                    <div class="card-header">
                      <h3 class="card-title">
                        <i>Update Hostel Block</i>
                      </h3>
                    </div>
                    <div class="card-body">
                      <div class="tab-content p-0">

                        <!-- {% if messages %}
                        {% for message in messages %}

                        <div class="alert alert-success">
                        {{ message }}

                        <button class="closebtn" onclick="this.parentElement.style.display='none';">&times;</button>
                    </div>
                        {% endfor %}
                        {% endif %} -->

                  <form class="px-md-2" method="POST" action="#">{% csrf_token %}

                                 <!-- {{ form|crispy }} -->

                    <input type="hidden" name="created_by" value="1" id="id_created_by" class="form-control" required>

                      <div class="form-group mb-2">
                        <label for="block_name">Block Name</label>
                        {{ form.block_name }}
                      </div>
    
                      <div class="form-group mb-2">
                        <label for="hostel_name">hostel</label>
                        {{ form.hostel_name }}
                      </div>

                  <button type="submit" class="btn btn-primary btn-lg mb-1">Update</button>

                  </form>

                      </div>
                    </div>
                  </div>

</section>
{% endblock content %}

hostel/templates/hostel/update_hostel.html
{% extends 'users/base.html' %}
{% load crispy_forms_tags %}


        {% block title %}
            HPRMS |    Update hostel
        {% endblock title %}
    

{% block content %}
{% load static %}

    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-12">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="{% url 'dashboard' %}">Home</a></li>
              <li class="breadcrumb-item active"><i>Update hostel</i></li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

<section class="h-100 h-custom" style="padding-left: 100px;">

              <div class="card col-lg-10">
                    <div class="card-header">
                      <h3 class="card-title">
                        <i>Update hostel</i>
                      </h3>
                    </div><!-- /.card-header -->
                    <div class="card-body">
                      <div class="tab-content p-0">

                        {% if messages %}
                        {% for message in messages %}

                        <div class="alert alert-success">
                        {{ message }}

                        <button class="closebtn" onclick="this.parentElement.style.display='none';">&times;</button>
                    </div>
                        {% endfor %}
                        {% endif %}

                  <form class="px-md-2" method="POST" action="#">{% csrf_token %}

                  <!--                {{ form|crispy }}-->

                    <input type="hidden" name="created_by" value="1" id="id_created_by" class="form-control" required>

                      <div class="form-group mb-2">
                        <label for="name">Name</label>
                        {{ form.name }}
                      </div>
    
                      <div class="form-group mb-2">
                        <label for="location">location</label>
                        {{ form.location }}
                      </div>

                  <button type="submit" class="btn btn-primary btn-lg mb-1">Update</button>

                  </form>

                      </div>
                    </div><!-- /.card-body -->
                  </div>
                  <!-- /.card -->
</section>
{% endblock content %}