HPRMSYSTEM/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('users/', include('django.contrib.auth.urls')),
                  path('', include('users.urls')),
                  path('users/', include('users.urls')),
                  path('problems_report/', include('problems_report.urls')),
                  path('hostel/', include('hostel.urls')),
                #   path('hostel_block/', include('hostel_block.urls'))

              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

problems_report/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('student_report_problem/', views.student_reports, name='student_report_problem'),
    path('student_reported_problems/', views.view_student_reports, name='student_reported_problems'),
    path('warden_report_problem/', views.warden_reports, name='warden_report_problem'),
    path('view_students_reported_problems/', views.view_reported_problem, name='view_students_reported_problems'),
    path('view_warden_report/', views.view_warden_report, name='view_warden_report'),
    path('wardens_report/', views.warden_reported_problem, name='wardens_report'),
    path('problem_feedback/', views.problem_feedback_view, name='problem_feedback'),
    path('student_feedback_Form/<str:problem_id>', views.student_problem_feedback_form, name='student_feedback_Form'),
    path('feedback_Form/<str:problem_id>', views.warden_problem_feedback_form, name='feedback_Form'),
    path('view_students_problems/', views.usab_manager_view_students_problem, name='view_students_problems'),
    path('feedback/<str:problem_id>', views.problem_approve, name='problem-solved'),
    path('feedback-goahead/<str:problem_id>', views.problem_decline, name='problem-goahead'),
    path('wdfeedback/<str:problem_id>', views.wd_problem_approve, name='problem-cleared'),
    path('wdfeedback-goahead/<str:problem_id>', views.wd_problem_decline, name='problem-not-cleared')
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView, PasswordChangeDoneView
from django.contrib.auth.views import PasswordResetView, PasswordResetConfirmView, PasswordResetDoneView
from django.contrib.auth.views import PasswordResetCompleteView
from django.urls import path, reverse_lazy
from . import views

urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('register/', views.user_register, name='register'),
    path('add_student/', views.add_student, name='add_student'),
    path('add_warden/', views.add_warden, name='add_warden'),
    path('users-list/', views.users_view, name='users-list'),
    path('update-student/<student_id>', views.update_student, name='update-student'),
    path('delete-student/<student_id>', views.delete_student, name='delete-student'),
    path('warden-list/', views.view_wardens, name='warden-list'),
    path('students-list/', views.view_students, name='students-list'),
    path('update-warden/<warden_id>', views.update_warden, name='update-warden'),
    path('delete-warden/<warden_id>', views.delete_warden, name='delete-warden'),
    path('dashboard/', views.homepage, name='dashboard'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('change-password/', PasswordChangeView.as_view(
        template_name='users/password_change.html',
        success_url=reverse_lazy('password_change_done')), name='change-password'),
    path('change password/done/', PasswordChangeDoneView.as_view(
        template_name='users/password_change_done.html'), name='password_change_done'),
    path('password reset/', PasswordResetView.as_view(template_name='users/password_reset_form.html'),
         name='password_reset'),
    path('password reset done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path(r'<uidb64>[0-9A-Za-z_\-]+/<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20}/$',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password reset complete/', PasswordResetCompleteView.as_view(
        template_name='users/password_reset_complete.html'), name='password_reset_complete')
]

hostel/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class hostel(models.Model):
    name = models.CharField(max_length=100)
    location = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, default='', on_delete=models.CASCADE)
    updated_at = models.DateTimeField(auto_now=True)
    objects = models.Manager()
    
    def __str__(self):
        return self.name


class hostel_block(models.Model):
    block_name = models.CharField(max_length=20)
    hostel_name = models.ForeignKey(hostel, default='', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, default='', on_delete=models.CASCADE)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.block_name


class room(models.Model):
    room_no = models.CharField(max_length=6)
    block_name = models.ForeignKey(hostel_block, default='', on_delete=models.CASCADE)
    hostel_name = models.ForeignKey(hostel, default='', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, default='', on_delete=models.CASCADE)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.room_no


class allocate_room(models.Model):
    student = models.ForeignKey(User, default='', on_delete=models.CASCADE)
    room = models.ForeignKey(room, default='', on_delete=models.CASCADE)
    block_name = models.ForeignKey(hostel_block, default='', on_delete=models.CASCADE)
    hostel_name = models.ForeignKey(hostel, default='', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.student


class allocate_block(models.Model):
    warden = models.ForeignKey(User, default='', on_delete=models.CASCADE)
    block_name = models.ForeignKey(hostel_block, default='', on_delete=models.CASCADE)
    hostel_name = models.ForeignKey(hostel, default='', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.warden

problems_report/models.py
from tkinter import CASCADE
from django.contrib.auth.models import User
from django.db import models
from hostel.models import hostel, hostel_block, room, allocate_room, allocate_block


# Create your models here.
class student_report_problem(models.Model):
    student = models.ForeignKey(User, default='', on_delete=models.CASCADE)
    problem_type = models.CharField(max_length=50)
    description = models.CharField(max_length=500)
    image = models.ImageField(blank=True, null=True, upload_to="images/" )
    allocateroom = models.ForeignKey(allocate_room, default='', on_delete=models.CASCADE)
    # hostel = models.ForeignKey(hostel, default='', on_delete=models.CASCADE)
    # block_name = models.ForeignKey(hostel_block, default='', on_delete=models.CASCADE)
    # room_name = models.ForeignKey(room, default='', on_delete=models.CASCADE)
    feedback = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = models.Manager()

    def __str__(self):
        return self.problem_type


class warden_report_problem(models.Model):
    warden = models.ForeignKey(User, default='', on_delete=models.CASCADE)
    problem_title = models.CharField(max_length=100)
    details = models.CharField(max_length=500)
    allocateblock = models.ForeignKey(allocate_block, default='', on_delete=models.CASCADE)
    # hostel = models.ForeignKey(hostel, default='', on_delete=models.CASCADE)
    # block_name = models.ForeignKey(hostel_block, default='', on_delete=models.CASCADE)
    feedback = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = models.Manager()

    def __str__(self):
        return self.problem_title
        

problems_report/forms.py
from django import forms
from django.contrib.auth.models import User

from hostel.models import allocate_block
from .models import student_report_problem, warden_report_problem
from hostel.models import hostel, hostel_block, room, allocate_room,allocate_block

# student problem report form
class studentReportProblemForm(forms.ModelForm):
    student = forms.ModelChoiceField(queryset=User.objects.all(),
                                    widget=forms.HiddenInput())
    allocateroom = forms.ModelChoiceField(queryset=allocate_room.objects.all(),
                                    widget=forms.HiddenInput())

    class Meta:
        model = student_report_problem
        fields = ('student', 'problem_type', 'image', 'description', 'allocateroom')

    # def clean_image(self):
    #     image_file = self.cleaned_data.get('image')
    #     if not image_file.name.endswith(".jpg"):
    #         raise forms.ValidationError("Look at your image file type")  
    #     return image_file


# warden problem report form
class wardenReportProblemForm(forms.ModelForm):
    warden = forms.ModelChoiceField(queryset=User.objects.all(),
                                    widget=forms.HiddenInput())
    allocateblock = forms.ModelChoiceField(queryset=allocate_block.objects.all(),
                                    widget=forms.HiddenInput())


    class Meta:
        model = warden_report_problem
        fields = ('warden', 'problem_title', 'details', 'allocateblock')


    # student problem report form
class sendFeedbackForm(forms.ModelForm):

    class Meta:
        model = student_report_problem
        fields = ('feedback',)
        

problems_report/views.py
from unicodedata import name
from django.shortcuts import render
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.db.models import F
from hostel.models import allocate_block, allocate_room, hostel, hostel_block, room
from .forms import studentReportProblemForm, wardenReportProblemForm, sendFeedbackForm
from .models import student_report_problem, warden_report_problem
from django.urls import reverse
from django.contrib.auth.models import User

# Create your views here.

@login_required
def student_reports(request):
 
    form = studentReportProblemForm(request.POST, request.FILES)

    # hostel__ = allocate_room.objects.filter(hostel_name_id = F('id'))
    # block__ = allocate_room.objects.filter(block_name_id = F('id'))
    # room__ = allocate_room.objects.filter(room_id = F('id'),block_name_id = F('id'), hostel_name_id = F('id'))
    allocateroom__ = allocate_room.objects.filter(student_id = request.user.id)

    if form.is_valid():
        form.save()
        instance = form.save(commit=False)
        instance.student = request.user
        instance.allocateroom = instance.allocateroom
        # instance.hostel = instance.hostel
        # instance.block_name = instance.block_name
        # instance.room_name = instance.room_name
        instance.save()
        messages.success(request, "Your problem has been reported successfully")

        return redirect('student_report_problem')

    context = {
        'form': form,
        'allocate_room' : allocateroom__,
        }

    return render(request, 'problems_report/student/student_problem_report_form.html', context)


@login_required
def warden_reports(request):

    # block__ = allocate_block.objects.filter(block_name_id = F('id'), hostel_name_id = F('id'))
    form = wardenReportProblemForm(request.POST)
    
    allocateblock__ = allocate_block.objects.filter(warden_id = request.user.id)

    if form.is_valid():
        form.save()
        instance = form.save(commit=False)
        instance.warden = request.user
        instance.allocateblock = instance.allocateblock
        # instance.hostel = instance.hostel
        # instance.block_name = instance.block_name
        instance.save()
        messages.success(request, "Your problem has been reported successfully")

        return redirect('warden_report_problem')

    context = {
        'form': form,
        'allocate_block':allocateblock__,
    }

    return render(request, 'problems_report/warden/warden_problem_report_form.html', context)


# A problem reported by a specific student function
def view_student_reports(request):

    spr = student_report_problem.objects.filter(student_id=request.user.id).select_related('allocateroom')

    context = {

        'student_report_problem': spr,

    }

    return render(request, 'problems_report/student/problem_reported_by_student.html', context)


# All problems reported by all warden function
def warden_reported_problem(request):
    
    wardens = warden_report_problem.objects.all().select_related('allocateblock')

    context = {
        'warden_report_problem': wardens,
    }
    return render(request, 'problems_report/usab_manager/warden_reports.html', context)


# All problems reported by all studentsb
def view_reported_problem(request):

    # student_in_block = allocate_room.objects.get(student_id=student_report_problem.student_id, block_name = allocate_block.block_name)
    reports = student_report_problem.objects.all().select_related('allocateroom')

    # student_id=student_in_block

    context = {

        'student_report_problem': reports,

    }

    return render(request, 'problems_report/warden/reported_problem_by_students.html', context)


# A problems reported by a single warden function
def view_warden_report(request):

    wpr = warden_report_problem.objects.filter(warden_id = request.user.id).select_related('allocateblock')

    context = {
        'warden_report_problem': wpr,
    }

    return render(request, 'problems_report/warden/problem_reported_by_warden.html', context)


# Data feedback
def problem_feedback_view(request, problem_id):

    feedback_form_ = student_report_problem.objects.get(pk = problem_id)
    
    if request.method == 'POST':
        form = sendFeedbackForm(request.POST, instance = feedback_form_)
        if form.is_valid:
            form.save
    else:
        return render(request, 'problems_report/warden/reported_problem_by_students.html', context)
    context = {

        'form': form,
        
    }

    return render(request, 'problems_report/warden/reported_problem_by_students.html', context)


@login_required
def student_problem_feedback_form(request, problem_id):

    feedback_form = student_report_problem.objects.get(pk = problem_id)

    context = {

        'student_report_problem': feedback_form,
    }

    return render(request, 'problems_report/warden/feedback_form.html', context)


@login_required
def warden_problem_feedback_form(request, problem_id):

    warden_feedback_form = warden_report_problem.objects.get(pk = problem_id)

    context = {

        'warden_report_problem': warden_feedback_form,
    }

    return render(request, 'problems_report/usab_manager/feedback_form.html', context)


@login_required
def usab_manager_view_students_problem(request):

    reports = student_report_problem.objects.all().select_related('allocateroom')

    context = {

        'student_report_problem': reports,

    }

    return render(request, 'problems_report/usab_manager/students_reports.html', context)


@login_required
def problem_approve(request, problem_id):
    srp = student_report_problem.objects.get(id=problem_id)
    srp.feedback = 1
    srp.save()
    return HttpResponseRedirect(reverse("view_students_reported_problems"))


@login_required
def problem_decline(request, problem_id):
    srp_decline = student_report_problem.objects.get(id=problem_id)
    srp_decline.feedback = 2
    srp_decline.save()
    return HttpResponseRedirect(reverse("view_students_reported_problems"))


@login_required
def wd_problem_approve(request, problem_id):
    wrp = warden_report_problem.objects.get(id=problem_id)
    wrp.feedback = 1
    wrp.save()
    return HttpResponseRedirect(reverse("wardens_report"))


@login_required
def wd_problem_decline(request, problem_id):
    wrp_decline = warden_report_problem.objects.get(id=problem_id)
    wrp_decline.feedback = 2
    wrp_decline.save()
    return HttpResponseRedirect(reverse("wardens_report"))

problems_report/templates/problems_report/student/problem_reported_by_student.html
{% extends 'users/base.html' %}


{% block title %}
    HPRMS | Student Incidence reported
{% endblock title %}

{% load static %}

{% block content %}

<div class="content-header">
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><a href="{% url 'dashboard' %}">Home</a></li>
          <li class="breadcrumb-item active">{{ user.username }} Incidence reported</li>
        </ol>
      </div><!-- /.col -->
    </div><!-- /.row -->
  </div><!-- /.container-fluid -->
</div>

<section style="padding-left: 5px; padding-right: 5px;">
<div class="card">
  <div class="card-header">
    <h3 class="card-title"><i>{{ user.username }} Incidence reported</i></h3>
  </div>
  <!-- /.card-header -->
  <div class="card-body">
    <table id="example1" class="table table-bordered table-striped">
      <thead>
      <tr>
        <th>INDEX No</th>
        <th>ID</th>
        <th>Problem type</th>
        <th>Description</th>
        <th>Image</th>
        <th>Student</th>
        <th>Hostel</th>
        <th>Block</th>
        <th>Room</th>
        <th>Feedback</th>
      </tr>
      </thead>
      <tbody>
        {% for spr in student_report_problem %}
        <tr style="background-color: #fff;">
              <td>
                  <strong>
                      {{ forloop.counter }}
                  </strong>
              </td>
              <td>{{spr.id}}</td>
              <td>{{spr.problem_type}}</td>
              <td>{{spr.description}}</td>
               {% if spr.image %}
              <td>
                <img src="{{ spr.image.url }}" alt="Image problem" width="100px" height="50px">
              </td>
              {% else %}
              <td>
                Null
              </td>
              {% endif %}
              <td>{{spr.student}}</td>
              <td>{{spr.allocateroom.hostel_name}}</td>
              <td>{{spr.allocateroom.block_name}}</td>
              <td>{{spr.allocateroom.room}}</td>
              <td>
                {% if spr.feedback == 0 %}
                <I>Received, Waiting for feedback </I>
                {% elif spr.feedback == 1 %}
                <I class="text-success">Your Incident has been solved</I>
                {% elif spr.feedback == 2 %}
                <I class="text-danger">Please visit Usab Manager for more help</I>
                {% endif %}
              </td>

            </tr>

        {% endfor %}
      </tbody>
    </table>
  </div>
  <!-- /.card-body -->
</div>
</section>
{% endblock content %}

problems_report/templates/problems_report/student/student_problem_report_form.html
{% extends 'users/base.html' %}
{% load crispy_forms_tags %}


        {% block title %}
            HPRMS | student problem report form
        {% endblock title %}
    

{% block content %}
{% load static %}

    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row">
          <div class="col-sm-12">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="{% url 'dashboard' %}">Home</a></li>
              <li class="breadcrumb-item active"><i>Student problem report form</i></li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

<section class="h-100 h-custom" style="padding-left: 100px;">

              <div class="card col-lg-10">
                    <div class="card-header">
                      <h3 class="card-title">
                        <i>Student problem report form</i>
                      </h3>
                    </div><!-- /.card-header -->
                    <div class="card-body">
                      <div class="tab-content p-0">

                        {% if messages %}
                        {% for message in messages %}

                        <div class="alert alert-success">
                        {{ message }}

                        <button class="closebtn" onclick="this.parentElement.style.display='none';">&times;</button>
                    </div>
                        {% endfor %}
                        {% endif %}

                  <form class="px-md-2" method="POST" enctype="multipart/form-data" action="#">{% csrf_token %}

                  <!--                {{ form|crispy }}-->
                  
                    <input type="hidden" name="student" value="1" id="id_student" class="form-control" required>

                    {% for rm in allocate_room %}
                    <input type="hidden" name="allocateroom" value="{{ rm.id }}" id="id_allocateroom" class="form-control" required>
                    {%endfor%}
                    <!-- {% for rm in allocate_room %}
                    <input type="hidden" name="hostel_id" value="{{ rm.hostel_name_id }}" id="id_hostel" class="form-control" required>

                    <input type="hidden" name="block_name" value="{{ rm.block_name_id }}" id="id_block_name" class="form-control" required>

                    <input type="hidden" name="room_name" value="{{ rm.room_id }}" id="id_room_name" class="form-control" required>
                    {% endfor %} -->

                  <div class="mb-3">
                  <label for="problem_type">Problem type</label>
                  <select class="form-control col-md-12" name="problem_type" id="problem_type" required>
                    <option name="problem_type" disabled selected="selected">---Select Option---</option>
                    <option name="problem_type">Emergency problem</option>
                    <option name="problem_type">Annual problem</option>
                    <option name="problem_type">Sick problem</option>
                    <option name="problem_type">Maternity problem</option>
                    <option name="problem_type">Paternity problem</option>
                  </select>
                    </div>


                  <div class="mb-2">
                  <label for="description">Description</label>
                  <textarea name="description" class="form-control" id="description" required>
                  </textarea>
                  </div>
                </div> 

                  <div class="form-group mb-2">
                    <label for="image">Image</label>
                    <input type="file" name="image" id="image" class="form-control">
                    <small>image format should be in .png, .jpg </small>
                  </div>

                  <!-- <div class="form-group mb-2">
                    <label>Hostel</label>
                    {{ form.hostel }}
                  </div>

                  <div class="row">
  
                    <div class="form-group mb-2 col-md-6">
                      <label>Block</label>
                      {{ form.block_name }}
                    </div>

                    <div class="form-group mb-2 col-md-6">
                      <label>Room</label>
                      {{ form.room_name }}
                    </div>
                  </div> -->


                  <button type="submit" class="btn btn-primary btn-lg mb-1">Submit</button>

                  </form>

                      </div>
                    </div><!-- /.card-body -->
                  </div>
                  <!-- /.card -->
</section>
{% endblock content %}